name: Release

on:
  push:
    tags:
      - "v*" # e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: npx electron-forge publish --make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
